// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QAssessment_project.Data;

#nullable disable

namespace QAssessment_project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250319052914_santosh4")]
    partial class santosh4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QAssessment_project.Model.AssessmentDescription", b =>
                {
                    b.Property<int>("AssessmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentID"));

                    b.Property<DateTime>("DateConducted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("AssessmentID");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("QAssessment_project.Model.AssessmentScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTaken")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsTaken")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentID");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AssessmentScores");
                });

            modelBuilder.Entity("QAssessment_project.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ResetTimeExpires")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("RoleID");

                    b.ToTable("Employees");

                    b.HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "sridevi@gmail.com",
                            JoinedDate = new DateTime(2025, 3, 19, 5, 29, 14, 225, DateTimeKind.Utc).AddTicks(7927),
                            Password = "$2a$11$bEDymHrpLakbTUZw30WoxOHWlQqCjDeAjaQch.uCbEmH9KijW1Wze",
                            ResetToken = "",
                            RoleID = 3,
                            Username = "Sridevi"
                        });
                });

            modelBuilder.Entity("QAssessment_project.Model.EmployeeResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("QuestionID")
                        .HasColumnType("int");

                    b.Property<string>("SelectedOption")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("QuestionID");

                    b.ToTable("EmployeeResponses");
                });

            modelBuilder.Entity("QAssessment_project.Model.Question", b =>
                {
                    b.Property<int>("QuestionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionID"));

                    b.Property<string>("CorrectAns")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExamID")
                        .HasColumnType("int");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionID");

                    b.HasIndex("ExamID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("QAssessment_project.Model.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasAnnotation("SqlServer:Identity", "1, 1");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "User"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 3,
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleID = 4,
                            RoleName = "Guest"
                        });
                });

            modelBuilder.Entity("QAssessment_project.Model.AssessmentScore", b =>
                {
                    b.HasOne("QAssessment_project.Model.AssessmentDescription", "Assessment")
                        .WithMany("AssessmentScores")
                        .HasForeignKey("AssessmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QAssessment_project.Model.Employee", "Employee")
                        .WithMany("AssessmentScores")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("QAssessment_project.Model.Employee", b =>
                {
                    b.HasOne("QAssessment_project.Model.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QAssessment_project.Model.EmployeeResponse", b =>
                {
                    b.HasOne("QAssessment_project.Model.AssessmentDescription", "Assessment")
                        .WithMany("EmployeeResponses")
                        .HasForeignKey("AssessmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QAssessment_project.Model.Employee", "Employee")
                        .WithMany("EmployeeResponses")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QAssessment_project.Model.Question", "Question")
                        .WithMany("EmployeeResponses")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Employee");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QAssessment_project.Model.Question", b =>
                {
                    b.HasOne("QAssessment_project.Model.AssessmentDescription", "Assessment")
                        .WithMany("Questions")
                        .HasForeignKey("ExamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("QAssessment_project.Model.AssessmentDescription", b =>
                {
                    b.Navigation("AssessmentScores");

                    b.Navigation("EmployeeResponses");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QAssessment_project.Model.Employee", b =>
                {
                    b.Navigation("AssessmentScores");

                    b.Navigation("EmployeeResponses");
                });

            modelBuilder.Entity("QAssessment_project.Model.Question", b =>
                {
                    b.Navigation("EmployeeResponses");
                });

            modelBuilder.Entity("QAssessment_project.Model.Role", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
